### ISSUE TITLE
When the stdout/stderr view has focus, pressing Ctrl+A should select only its contents

### ISSUE THREAD

**Issue by theres-waldo** [Pernosco/pernosco#1]
**STR**

1. Load a pernosco session.
2. Give focus to the stdout/stderr view.
3. Press Ctrl+A.

**Expected results**

The contents of the stdout/stderr view are seleted.

**Actual results**

The contents of all views are selected.

**Comment by khuey** [comment]
Fixed in 44d0809527f094a886af3e694b0f0ef10cbc5681.
