### ISSUE TITLE
Printing local variables in the "executions of a line" view sometimes doesn't work

### ISSUE THREAD

**Issue by theres-waldo** [Pernosco/pernosco#12]
**Steps to reproduce**

  1. Open [this recording](https://pernos.co/debug/iQ1p9BsVtB2OoQ6y-8WtVg/index.html)
  2. Open the executions of `nsLayoutUtils::ComputeScrollMetadata` and select any one
  3. In the Source view, click on line 9021. Observe that on this line, a variable named `scrollId` whose type (after typedef resolution) is `uint64_t`, is in scope.
  4. In the "executions of nsLayoutUtils.cpp:9021" view, enter "scrollId" into the expression to print field

**Expected results**

Each execution prints a numeric value.

**Actual results**

Each execution just prints the characters "scrollId".

**Comment by khuey** [comment]
Thanks for reporting. We aren't traversing the scope chain correctly here. This is fixed (71686639674ea19bbb83e79516a1cc94ab7f567e) and will deploy in a day or so.
