### ISSUE TITLE
Update wiki page on reproducing taskcluster failures after Firefox taskcluster transition and upgrade

### ISSUE THREAD

**Issue by asutherland** [Pernosco/pernosco#15]
The docs at https://github.com/Pernosco/pernosco/wiki/Mozilla-Tips#reproducing-arbitrary-taskcluster-job-failures explain how to use the self-serve API, but it's no longer clear how to get the task group ID for runs.

Specifically, I documented the steps I'd used at one point at https://bugzilla.mozilla.org/show_bug.cgi?id=1594572#c11
- This was when the taskcluster UI looked like https://clicky.visophyte.org/files/screenshots/20200304-094630.png which was very explicit about the group ID
- Now when I click on the task ID of something in taskcluster, it looks like https://clicky.visophyte.org/files/screenshots/20200304-094651.png and there are things I can click on to expand them, but nothing seems to actually be a group id.

Thanks!

**Comment by khuey** [comment]
You need to click "see more" at the bottom of the left hand column and then scroll all the way down to the bottom and find something that looks like : `"parent": "d2K0vo-8Tg6naOFPUOGCWg"`

That is the task group id.

**Comment by asutherland** [comment]
Aha!  Let me know if you'd like me to try my hand at some markdown you can copy into https://github.com/Pernosco/pernosco/wiki/Mozilla-Tips#reproducing-arbitrary-taskcluster-job-failures.

**Comment by rocallahan** [comment]
FWIW if you click on "Task Group" the group ID is in the URL.

**Comment by jensstutte** [comment]
I am trying to follow those instructions and found the parent id, but I get a "Failure! Contact support.". I tried https://pernos.co/self-service-api/mozilla/eWxUDMQ4RPS3AYUWI5UKKw/IAmk4jm0QP6Rwj9xo4RAsw/self-service.html for task https://firefox-ci-tc.services.mozilla.com/tasks/IAmk4jm0QP6Rwj9xo4RAsw.

**Comment by rocallahan** [comment]
That error message isn't good, but the reason it's failing is because that task is a Windows task. Pernosco only supports reproduction of Linux failures.

**Comment by jensstutte** [comment]
Should have checked before, of course... sorry for the noise

**Comment by khuey** [comment]
Docs updated, and there's some new feedback about unsupported job types if you try to trigger then.

**Comment by asutherland** [comment]
Thank you!
