### ISSUE TITLE
Filtering function executions with a condition using arrays doesn't appear to work

### ISSUE THREAD

**Issue by glandium** [Pernosco/pernosco#17]
- Open https://pernos.co/debug/-MejP2XDlfeN3zKoEx9Y6w/index.html
- Search for `simplify_commit`
- Add a condition for `commit.object.oid.hash[0] == 0x37`

(Note in this specific case, it would be even better if it were possible to test for a slice, because `commit.object.oid.hash[0] == 0x37 && commit.object.oid.hash[1] == 0x54 && commit.object.oid.hash[2] == 0xd0` is tedious)

**Comment by khuey** [comment]
`commit->object.oid.hash` appears to be a string, and not an array, which is why it's not working.

**Comment by glandium** [comment]
it's a `unsigned char[32]`, not a `char*`.
https://github.com/git/git/blob/master/hash.h#L182

**Comment by khuey** [comment]
Indeed, it is. The issue here is that our pretty printer rewrites it to be a string, and then array indexing no longer works on it.

So we'll have to think about how to approach this.

**Comment by khuey** [comment]
We did fix this at some point. We now try evaluations against the un-prettyprinted version if the pretty-printed version fails.

You also can apply a regex to the string to get the slice comparison behavior if you want that.
