### ISSUE TITLE
Function execution window doesn't find instance until it is located via another method.

### ISSUE THREAD

**Issue by mattwoodrow** [Pernosco/pernosco#20]
Trace: https://pernos.co/debug/fJdZQLw9CPTTovJuUnDnDg/index.html#f{m[Bbru,AA_,t[AsI,CZA_,f{e[Bbrs,Bz4_,s{af3YbVLAA,bARU,oBHy03A,uBG26tA___

STR:

* Open a window for executions of 'nsThread::nsThread', and filter with 'this==0x7f761a181890'
* Observe no results found.
* Use callees window to navigate into 'nsIEventTarget::IsOnCurrentThread'
* Open local variables window and expand entry for 'this'.
* Click on vptr address (0x7f762557aca0) to open a dataflow window.
* Click on the nsThread::nsThread entry (for 0x7f761a181890)  in the dataflow window
* Open a new nsThread::nsThread executions window, and filter.
* We should now find the desired ctor. If you still have the old window open you can see them showing different results.

**Comment by rocallahan** [comment]
Fix deployed!
