### ISSUE TITLE
triple clicking input fields implemented with contenteditable selects more than you'd expect

### ISSUE THREAD

**Issue by heycam** [Pernosco/pernosco#23]
The three input fields at the top of an Executions window are implemented with contenteditable.  I triple clicked one to select all of its contents (so I could type over it), but this selected the entire text contents of the header of the window.  Ctrl+A when focus is inside there does unexpected things to the selection.

**Comment by rocallahan** [comment]
It's actually double-clicking selecting a word that causes the problem --- when there's no whitespace between query parameters, Firefox allows word-selection to happen across the contenteditable boundary. Chrome doesn't.

I worked around it for Firefox by adding whitespace between the query parameters.
