### ISSUE TITLE
small error pretty printing nsCString

### ISSUE THREAD

**Issue by heycam** [Pernosco/pernosco#25]
See the attached screen shot.  The backslash shouldn't be there in the tooltip.

https://pernos.co/debug/LSfVKr1Sy-RmD0zzkn4sPg/index.html#f{m[AQiX,Rvcp_,t[RQ,EOI_,f{e[AQiX,RvKa_,s{af1h4P+AA,bAXY,oCAYePA,uCAWWfg___

![pretty](https://user-images.githubusercontent.com/1484434/87889518-64d6bb00-ca75-11ea-9246-4ab9dae83d7a.png)

**Comment by rocallahan** [comment]
This is because we're quoting Markdown incorrectly. We don't need to quote `"`, and if we do, we get this bug.

Fixing that is easy. Monaco Markdown treats the trailing `"` as part of the link though. I'm not going to worry about that.
