### ISSUE TITLE
Executions condition not matching as expected

### ISSUE THREAD

**Issue by heycam** [Pernosco/pernosco#26]
https://pernos.co/debug/vHltSmjIPyuPUoIgciED9g/index.html#f{m[Awh2,AlqA_,t[AUM,HaE_,f{e[Awh2,Alp2_,s{afx/j+mAA,bAXY,oAudIdQ,uAtABWg___

I want to filter the Executions display of `mozilla::dom::PContentChild::SendAccumulatePageUseCounters` with `aWindowContextID==2147483657`, which I can see from the unfiltered Exeuctions display was run.  But when I add the condition I'm told that there were no executions that match the condition.

**Comment by khuey** [comment]
`aWindowContextID` is a reference so we're actually trying to match against its internal pointer. That's both surprising and useless behavior, so we should "look through" the reference to the referent.

**Comment by khuey** [comment]
Fixed internally in d2485884c6dca20e9010f28facac0e7b40ae7fcf, should deploy tomorrow.
