### ISSUE TITLE
Allow uploading an rr recording for indexing and subsequent debugging via Pernosco

### ISSUE THREAD

**Issue by theres-waldo** [Pernosco/pernosco#3]
Sometimes, an issue is much easier to trigger via interactive use than via an automated test on Treeherder. In such cases, it would be convenient to be able to upload a local rr recording to Pernosco for indexing.

Granted, if I have a local rr recording, the temptation to just replay it locally is pretty high, but depending on the situation, it may be worth waiting for Pernosco indexing.

**Comment by khuey** [comment]
Stay tuned ...

**Comment by rocallahan** [comment]
https://github.com/Pernosco/pernosco-submit allows this. I'll send you instructions directly.
