### ISSUE TITLE
"compiler broken" shown in dataflow toolbox

### ISSUE THREAD

**Issue by heycam** [Pernosco/pernosco#30]
STR:

1. Open [this trace](https://pernos.co/debug/rjFkI_2uDqftYHle21wccw/index.html#f{m[AqqR,FqD6_,t[RA,C4I_,f{e[AqqR,O+k_,s{af/fFJ2AA,bARY,uHWO9uw,oHWQoVw___).
2. Open the Instructions Executed toolbox.
3. Click on the `0xffceced3` in the highlighted instruction.
4. Dataflow toolbox shows "0x7ff7978b2590: compiler broken".

**Comment by khuey** [comment]
Thanks, fixed internally.
