### ISSUE TITLE
Feature Suggestion: Trace Descriptions

### ISSUE THREAD

**Issue by georgewsinger** [Pernosco/pernosco#32]
It would be nice to be able to attach a short description next to a trace to keep track of which one is for which bug:

![image](https://user-images.githubusercontent.com/10677444/102383120-3532cd00-3f99-11eb-8e9f-6f1dddac630b.png)

Perhaps this could be added to the pernosco-submit API?

```
pernosco-submit upload <trace> <source> --description="Firefox popups issue"
```

**Comment by khuey** [comment]
Have you discovered the `--title` argument?

**Comment by georgewsinger** [comment]
> The --title option lets you specify a title for the upload. This title is quoted in notification emails from Pernosco, appears in the browser tab title for a Pernosco session, and appears in the top right of the Pernosco window. The --url option lets you specify a URL which the title text links to.

That's pretty much what I requested, which is already implemented :]
