### ISSUE TITLE
Merged executions window lack different colors as odd/even backgrounds

### ISSUE THREAD

**Issue by julienw** [Pernosco/pernosco#35]
A normal "Executions" window has a grey-and-white background, for odd/even lines.

As soon as 2 executions windows are merged, this doesn't happen, and everything has white backgrounds. This makes it difficult to distinguish the lines.

![image](https://user-images.githubusercontent.com/454175/108534377-5f2aa780-72da-11eb-806e-4d319e0043f7.png)

**Comment by khuey** [comment]
@rocallahan we need to do something more principled here. Right now we whitelist views and we don't include the `join` view, hence this bug, we also don't want to do all list views because we don't want to do this for stdout.

**Comment by asutherland** [comment]
Many of the stdout/stderr things I see from Firefox end up line-wrapped on my display; as long as the zebra-striping only changes on the hard wrapping (newlines, not wraparound), that seems like it might be a nice enhancement?

**Comment by khuey** [comment]
If we applied this to stdout/err it would be highlighting distinct writes, not entire lines. So write(2, "foo\nbar") would produce two lines in the display with the same highlight.

**Comment by khuey** [comment]
stdout/err is mergable with any other list view, so perhaps we should just bite the bullet and do that.

**Comment by khuey** [comment]
This is also complicated by our DOM structure. We put the things from each subquery into a `subqueryItemsContainer` div, so we can't use :nth-last-of-type on the individual `pml_block` divs.

**Comment by julienw** [comment]
The main problem is that the lines are difficult to distinguish in merged panels. Maybe the odd/even coloring isn't the right solution then, given the DOM.

Would it be possible to add some margin between execution lines?

Other ideas:
* some icon at the start of each execution line
* highlight all lines for an execution query when hovering its title in the header

Thanks!

**Comment by julienw** [comment]
I tried this:
```css
.listView-item::before {
  content: "𝒇   "; /* These spaces are non-breakable spaces */
}
.listview-item {
  margin: .3rem 0
}
```
This works quite well for me. Not perfect, but at least better.

**Comment by rocallahan** [comment]
We'll deploy this shortly:
![image](https://user-images.githubusercontent.com/296135/112567432-b5dd5100-8e45-11eb-95b1-f237ac367f23.png)
