### ISSUE TITLE
Search bar view proposals don't handle overflow cases involving lambdas well

### ISSUE THREAD

**Issue by asutherland** [Pernosco/pernosco#36]
I'm not honestly entirely sure what's going on here, but if you open up [this mozilla pernosco link](https://pernos.co/debug/rfjjlbVcOQIDzPO0In1yuw/index.html#f{m[AZ8D,Dp33_,t[2g,PYiL_,f{e[AZ8D,Dp25_,s{afxNlgeAA,bAXs,uF6wxIg,oF7xguA___) and search on `OpenDatabaseOp::LoadDatabaseInformation` you will see something like this
![image](https://user-images.githubusercontent.com/212206/109077362-00926e80-76ca-11eb-84a8-bddb51b722a2.png)

If you check out [the code](https://searchfox.org/mozilla-central/rev/31a3457890b5698af1277413ee9d9bd6c5955183/dom/indexedDB/ActorsParent.cpp#16127) you'll see we use lots of cool (nested) lambdas inside it and these seem to result in very long pretty-printed symbols that may be at the root of the problem.

**Comment by khuey** [comment]
The `#searchDropdown > buttons` are not `overflow: hidden`. Their contents are, but that doesn't seem to matter (maybe this is an interaction with flexbox?)

Even after adding `overflow: hidden` on those it's not amazing but it's definitely far less insane. 
![](https://user-images.githubusercontent.com/325892/109080187-f9ad3100-76b4-11eb-9d29-4979359c4e7c.png)

**Comment by asutherland** [comment]
Thanks!  I applied the CSS and (as in your screenshot) that's a pretty good improvement and lets me find the actual method without all the lambdas all over the place!

**Comment by khuey** [comment]
Separately, we should probably figure out a way to rank lambdas lower here.

**Comment by khuey** [comment]
This will be fixed next time we deploy.

The "real" function is already ahead of all the lambdas, so I think we're good there too.
