### ISSUE TITLE
Source view doesn't provide line execution markers or the ability to set line number breakpoints/execution queries for contained lambdas

### ISSUE THREAD

**Issue by asutherland** [Pernosco/pernosco#37]
After having worked around https://github.com/Pernosco/pernosco/issues/36 via Kyle's help, I end up [in this mozilla pernosco trace frame](https://pernos.co/debug/rfjjlbVcOQIDzPO0In1yuw/index.html#f{m[AZ+j,lmc_,t[Vw,PYcl_,f{e[AZ+j,lmc_,s{afxNlgeAA,bAXs,uF6wxIg,oF7+L7A___) in this [zealousy lambda-using code](https://searchfox.org/mozilla-central/rev/31a3457890b5698af1277413ee9d9bd6c5955183/dom/indexedDB/ActorsParent.cpp#16127) that builds on [QM_TRY](https://searchfox.org/mozilla-central/rev/31a3457890b5698af1277413ee9d9bd6c5955183/dom/quota/QuotaCommon.h#98) a fancier version of [MOZ_TRY](https://searchfox.org/mozilla-central/rev/31a3457890b5698af1277413ee9d9bd6c5955183/mfbt/Result.h#773) which is inspired by rust's `try!`.  The basic idea is that every tried expression uses a lambda which will be synchronously executed inside the function call one or more times, plus there are a number of helpers including the [looping helper CollectWhileHasResult](https://searchfox.org/mozilla-central/rev/31a3457890b5698af1277413ee9d9bd6c5955183/dom/indexedDB/ActorsParent.cpp#16178).

In a more traditionally structured function, pernosco would let me click on line numbers to set breakpoints and show which lines were executed.  It would be really fantastic if pernosco could treat these lambda invocations as occurring within the top-level function invocation, or at the very least let me set line breakpoints in them so that I can use that to get into the right frame.  The Callees view does expose some of the lambdas, but I think the way many of them are indirectly called means that I can't usefully traverse in without line breakpoints.

Screenshot: 
![image](https://user-images.githubusercontent.com/212206/109086662-06904b80-76da-11eb-9f2c-2027c828b50b.png)

**Comment by asutherland** [comment]
Addendum: It's possible I'm making assumptions about what code gets run (and maybe a line number that you can't click on to create a breakpoint means pernosco thinks that line of code is never run in the entire trace?).  But, for example, [this call to GetFileManager](https://pernos.co/debug/rfjjlbVcOQIDzPO0In1yuw/index.html#f{m[AZo7,A1un_,t[Vw,PYcl_,f{e[AZo7,A1ud_,s{afxNlgeAA,bAXs,uF/0D4w,oGAlubA___) is definitely happening, but when I go up to the outer frames there's no evidence of the code on line 16065 getting called, although it seems like it definitely is.

**Comment by khuey** [comment]
Unfortunately this appears to be a compiler bug.

**Comment by khuey** [comment]
IDB_TRY_INSPECT seems to confuse clang. Regular lambdas in clang 11 work fine in a small test case I did. I suspect that wrapping it in a macro is destroying the line numbers in the preprocessor. I don't think there's much we can do here without better debug info from the compiler :(

**Comment by asutherland** [comment]
Thank you very much for investigating!  We'll see what we can do about fixing clang and/or our macrology.  Thankfully the clang++ `-Xclang -ast-dump=json -fsyntax-only` JSON AST-dumping mechanism can be pretty handy (in files that are smaller than IndexedDB's ActorsParent.cpp).

**Comment by khuey** [comment]
It would be interesting to see what turning on https://clang.llvm.org/docs/UsersManual.html#controlling-macro-debug-info-generation does. I don't know exactly what information that emits so idk how useful it would be. It would probably require Pernosco-side work to use it.
