### ISSUE TITLE
Add/remove column buttons are labeled confusingly

### ISSUE THREAD

**Issue by tbodt** [Pernosco/pernosco#42]
These buttons are confusing. I can never remember which is add and which is remove, so I often accidentally remove a column when I wanted to add one. I think they should be labeled something like `+` and `-`.

<img width="32" alt="image" src="https://user-images.githubusercontent.com/5678977/111104105-25317780-850d-11eb-8e0a-ee0772de5f51.png">

**Comment by rocallahan** [comment]
![image](https://user-images.githubusercontent.com/296135/111258681-57b0b100-8682-11eb-865a-41f606700151.png)

**Comment by tbodt** [comment]
Screenshot looks nice! The icon font seems to be blocked by the CSP though: 
<img width="1601" alt="image" src="https://user-images.githubusercontent.com/5678977/111258861-07cadf00-85db-11eb-9890-f7180c6935eb.png">

```
content-security-policy: default-src 'self' github.com;script-src 'self' 'sha256-ih8uGBHZhNa8RYX6VNKy3/buYTmJD3KJ+JyIRzUB4s4=' https://static.pernos.co;connect-src 'self' data: wss://pernos.co https:;style-src 'self' 'unsafe-inline' https://static.pernos.co;img-src 'self' data: https://static.pernos.co;child-src 'self' blob: https://static.pernos.co;frame-ancestors 'none';base-uri 'none';object-src 'none';form-action 'none'
```

**Comment by rocallahan** [comment]
Interesting, works in Firefox, but Chrome blocks it. Not sure why it works in Firefox.

**Comment by tbodt** [comment]
Huh, I'm using Firefox.

**Comment by rocallahan** [comment]
OK, maybe it's something to do with my local environment.

Anyway, fix is in the works.

**Comment by rocallahan** [comment]
Fix deployed. Works for me in Chrome now.
