### ISSUE TITLE
Call `GetSpecOrDefault()` automatically when using a nsIURI for printing and matching

### ISSUE THREAD

**Issue by julienw** [Pernosco/pernosco#43]
It would be nice to access `GetSpecOrDefault()` when referencing a `nsIURI` variable for printing and matching (in conditions):
https://searchfox.org/mozilla-central/source/__GENERATED__/dist/include/nsIURI.h#55

Of course it should still be possible to access other values too.

If that's not possible, accessing `mSpec` of `nsStandardURL` would be good enough for my use cases:
https://searchfox.org/mozilla-central/rev/4e87b5392eafe1f1d49017e76f7317b06ec0b1d8/netwerk/base/nsStandardURL.h#263-264

Thanks!

**Comment by khuey** [comment]
Doing `nsStandardURL::mSpec` is pretty easy. Automatically invoking user functions like `GetSpecOrDefault()` is a bit problematic for us (it's slow, for one). I don't think we'll want to do that.

**Comment by khuey** [comment]
I will note that you should be able to write myURI->GetSpecOrDefault() in an expression and have it work. If that doesn't work that's a separate bug.

**Comment by julienw** [comment]
Example:
1. open [this debug link](https://pernos.co/debug/a2d2wz6tiEOKWTyMzkl5Nw/index.html#f{m[BMBD,BuGy_,t[AQ,WHY_,f{e[BMBD,BuGX_,s{afy2sZjAA,bAWE,uAoudbg,oAppNtQ___)
2. search for executions of `profiler_add_network_marker`
3. `aURI` is the first argument for this function

**Comment by khuey** [comment]
I don't think we're going to do this. Rewriting this way discards too much information for it to be done by default, at least while we have no way to prevent rewriting.
