### ISSUE TITLE
Deferencing a `nsCOMPtr` pointer to access a property doesn't seem to always work

### ISSUE THREAD

**Issue by julienw** [Pernosco/pernosco#45]
STR:
1. open [this debug link](https://pernos.co/debug/a2d2wz6tiEOKWTyMzkl5Nw/index.html#f{m[BMBD,BuGy_,t[AQ,WHY_,f{e[BMBD,BuGX_,s{afy2sZjAA,bAWE,uAoudbg,oAppNtQ___)
2. search for executions of `mozilla::net::nsHttpChannel::OnStopRequest`
3. print `mURI.mRawPtr->mSpec` => this works
5. print `mURI->mSpec` => this doesn't work

This is implemented in https://searchfox.org/mozilla-central/rev/4e87b5392eafe1f1d49017e76f7317b06ec0b1d8/netwerk/base/nsBaseChannel.h#291

**Comment by khuey** [comment]
This will be fixed on our next deployment.
