### ISSUE TITLE
Support "bitwise AND" aka `&` in expressions.

### ISSUE THREAD

**Issue by asutherland** [Pernosco/pernosco#48]
Necko channel load flags use cool bitmask constants [like LOAD_DOCUMENT_URI](https://searchfox.org/mozilla-central/rev/e08a9aa5c5dfb77e8847ab7af3f753a9c3e551f8/netwerk/base/nsIChannel.idl#210).  It would be handy to do things like set a condition of `aLoadFlags & LOAD_DOCUMENT_URI` or a print.  (To be clear, I can already do a print of `LOAD_DOCUMENT_URI + 1 - 1` and see the value `65536`, so the literal translation is already handled awesomely.)

It would also be great to have bitwise OR as well.

**Comment by khuey** [comment]
bitwise and, or, and xor are all available now on new traces.
