### ISSUE TITLE
GDB window ending up in `syscall_traced`

### ISSUE THREAD

**Issue by mgaudet** [Pernosco/pernosco#51]
👋 I've got a [trace](https://pernos.co/debug/wnYsYUnvHnhZo0vx9vg8qQ/index.html#f{m[tPs,AA_,t[aQ,Nncg_,f{e[S6g,KBk_,s{af/dYs5AA,bLA,uH9OQGA,oH9OUCQ___/) where frequently when I jump to another point in the trace by clicking (eg, in the notebook), the gdb terminal loses sync and says we're in 

```
0x0000000070000002 in syscall_traced ()
```

Restarting the GDB window has worked reliably for me.

**Comment by khuey** [comment]
When you're clicking around are you jumping processes? The gdb panel is fixed to a particular process, and that process might be in futex_wait or similar while the other process is running?

**Comment by mgaudet** [comment]
Oh, almost certainly yes -- I was hunting for a particular call (I should open a new issue about conditional execution) 

Perhaps a message indicating that the shell is tied to a process when jumping outside the bounds would help.

**Comment by khuey** [comment]
> (I should open a new issue about conditional execution)

Please do.

**Comment by khuey** [comment]
Going forward we will display this.

![image](https://user-images.githubusercontent.com/325892/162276055-2e4e3789-3270-473e-80f7-41f556337e1e.png)

**Comment by mgaudet** [comment]
That’s perfect! Informative and actionable!
