### ISSUE TITLE
Conditional filtering of executions doesn't support any complexity in expression?

### ISSUE THREAD

**Issue by mgaudet** [Pernosco/pernosco#52]
In a [trace](https://pernos.co/debug/wnYsYUnvHnhZo0vx9vg8qQ/index.html#f%7Bm%5BtPs,AA_,t%5BaQ,Nncg_,f%7Be%5BS6g,KBk_,s%7Baf/dYs5AA,bLA,uH9OQGA,oH9OUCQ___/), I was looking for a particular call, where `GetNameOperation`'s `name` argument pointed to a string `ReadableStream`

While I was able to print the `names` associated with the calls by putting `**(name.ptr).d.inlineStorageLatin1` in the print box, I couldn't filter out calls to look for ReadableStream by doing for example `**(name.ptr).d.inlineStorageLatin1[0] == 'R'` in the condition box. It just was annoyed and printed lots of the expression in red. 

I'm not sure what the limitations are in the condition, but it was frustrating that print would work, but filtering based on *very similar information* wouldn't.

**Comment by khuey** [comment]
You probably want `**(name.ptr).d.inlineStorageLatin1 =~ m/^R/`, maybe plus the "hide invalid conditions" button that appears on mouseover on the red. I think there's some issues here with string handling that I'll look into.

**Comment by khuey** [comment]
This was caused by incorrect handling of character/string literals. Going forward both `**(name.ptr).d.inlineStorageLatin1[0] == 'R'` and `**(name.ptr).d.inlineStorageLatin1 == "ReadableStream"` will behave in the intuitive manner.
