### ISSUE TITLE
Pasting an address into the Values of Memory Address panel doesn't work

### ISSUE THREAD

**Issue by mgaudet** [Pernosco/pernosco#53]
... unless I first backspace out the existing 0xdeadbeef content (or other address).

**Comment by khuey** [comment]
I've made this change for when the initial value 0xdeadbeef is in the field.

I'm reluctant to do this in general though. Being able to write a condition like `foo.bar == ` and then paste in the pointer value is really useful. Currently all these input fields share the same logic. If this continues to be annoying in the non-initial-value case I'll have to split them apart so we can choose on a per-field basis what to do.
