### ISSUE TITLE
SIGILL attempting to call a function

### ISSUE THREAD

**Issue by mgaudet** [Pernosco/pernosco#6]
In [this Pernosco session](https://pernos.co/debug/xKHOWW-hDVBsrv78cxnprA/index.html#f{m[MGM,A1E_,t[AQ,N5E_,f{e[MFw,AiWY_,s{aVkla5kAA,bBA,oAuh3Jw,uAtaJ+w___) if you attempt to dump the value of `name` by calling `name->dump()` 

```
(pernosco) print name->dump() 

Program received signal SIGILL, Illegal instruction.
0x00007f8ac5c52268 in ?? () from /sysroot/lib64/ld-linux-x86-64.so.2
The program being debugged was signaled while in a function called from GDB.
GDB has restored the context to what it was before the call.
To change this behavior use "set unwindonsignal off".
Evaluation of the expression containing the function
(JSAtom::dump()) will be abandoned.
(pernosco) when 
Current event: 12387
```

This trace was uploaded using `pernosco-submit`, from an Ubuntu VM (`Linux ubuntu1904vm 5.0.0-15-generic #16-Ubuntu SMP Mon May 6 17:41:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`)

**Comment by mgaudet** [comment]
(oh, curious. That link doesn't go quite where I thought it would if you click it from github and open a new tab; but if you then paste the same link into the address bar, it does go where I roughly would expect; the pane layout is different, but it seems to be at least on the right line)

**Comment by khuey** [comment]
Github has truncated the URL, and your workaround doesn't seem to work for me.  Can you put the whole link in a ```preformated``` block?

**Comment by mgaudet** [comment]
Curious; the edit view preserves the original link; but anyhow: 

```
https://pernos.co/debug/xKHOWW-hDVBsrv78cxnprA/index.html#f{m[MGM,A1E_,t[AQ,N5E_,f{e[MFw,AiWY_,s{aVkla5kAA,bBA,oAuh3Jw,uAtaJ+w___
```

Should take you to the right place!

**Comment by khuey** [comment]
Great, thanks.

**Comment by khuey** [comment]
This is fixed now.
